name: binary_clock
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
  

dependencies:
  flutter:
    sdk: flutter

  intl:
  rxdart:

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
  - family: Alatsi
    fonts:
      - asset: fonts/Alatsi-Regular.ttf
